yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views
from .views import PostDeleteView

app_name = 'posts'

urlpatterns = [
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('follow/', views.follow_index, name='follow_index'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/delete/',
         PostDeleteView.as_view(), name='post_delete'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('', views.index, name='index'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts'))
]

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from core.models import CreatedModel
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(CreatedModel):
    text = models.TextField(
        verbose_name='Текст',
        help_text='Введите текст поста')
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Опубликовано')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор')
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост')
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True)

    class Meta:
        ordering = ('-pub_date',)
        verbose_name_plural = 'Посты'
        verbose_name = 'Пост'

    def __str__(self):
        return self.text[:settings.POST_TEXT_SHORT]


class Group(CreatedModel):
    title = models.CharField(max_length=200, verbose_name='Группа')
    slug = models.SlugField(unique=True, verbose_name='Адрес группы')
    description = models.TextField(verbose_name='Описание группы')

    class Meta:
        verbose_name_plural = 'Группы'
        verbose_name = 'Группа'

    def __str__(self):
        return self.title


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментарий')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор')
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария')

    class Meta:
        ordering = ('-created',)
        verbose_name_plural = 'Комментарии'
        verbose_name = 'Комментарий'

    def __str__(self):
        return self.text[:settings.POST_TEXT_SHORT]


class Follow(CreatedModel):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор')

    class Meta:
        verbose_name_plural = 'Подписчики'
        verbose_name = 'Подписчик'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique follow')
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        widgets = {
            'text': forms.Textarea(attrs={
                'placeholder': 'Введите текст поста',
                'class': 'form-control',
            }),
            'group': forms.Select(attrs={'class': 'form-control'})
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.Textarea(attrs={
                'placeholder': 'Введите текст комментария',
                'class': 'form-control',
                'rows': 4,
                'cols': 20,
            }),
        }

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import DeleteView

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import paginator


def index(request):
    post_list = Post.objects.all()
    page_obj = paginator(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = paginator(request, post_list)
    context = {
        'group': get_object_or_404(Group, slug=slug),
        'page_obj': page_obj, }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    page_obj = paginator(request, post_list)
    posts_amount = author.posts.count()
    following_list = Follow.objects.filter(
        user=request.user.id, author=author.id).all()
    if len(following_list) > 0:
        following = True
    else:
        following = False
    context = {
        'author': author,
        'page_obj': page_obj,
        'posts': post_list,
        'posts_amount': posts_amount,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.all()
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.save()
            return redirect('posts:post_detail', post.id)
    else:
        form = CommentForm()
    context = {
        'post': post,
        'posts_amount': post.author.posts.count(),
        'title': post.text[:settings.POST_TEXT_SHORT],
        'form': form,
        'comments': comments,

    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(
            request.POST,
            files=request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', post.author.username)
    else:
        form = PostForm()
    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post.id)
    if request.method == "POST":
        form = PostForm(
            request.POST,
            files=request.FILES or None,
            instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('posts:post_detail', post.id)
    else:
        form = PostForm(instance=post)
    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


class PostDeleteView(DeleteView):
    model = Post
    pk_url_kwarg = 'post_id'
    template_name = 'posts/post_delete.html'
    success_url = reverse_lazy('posts:index')


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    follows = Follow.objects.filter(user=request.user)
    post_list = Post.objects.filter(author__in=follows.values('author'))
    page_obj = paginator(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    follower = request.user
    following_list = Follow.objects.filter(
        user=follower, author=author).all()
    if follower != author and len(following_list) == 0:
        Follow.objects.create(
            user=follower,
            author=author
        )
    return redirect(reverse('posts:profile', args={username, }))


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect(reverse('posts:profile', kwargs={'username': username}))

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %} {% if form.instance.pk %} Редактировать запись {% else %} Новая запись {% endif %} {% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                    {% if form.instance.pk %}
                        Редактировать запись
                    {% else %}
                        Новая запись
                    {% endif %}
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data"
                          action="{% if form.instance.pk %} {% url 'posts:post_edit' form.instance.pk %} {% else %} {% url 'posts:post_create' %}{% endif %}">
                        {% load user_filters %}
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group row my-3">
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                    {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
                                </label>
                                {{ field|addclass:'form-control' }}
                                {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class="d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">
                                {% if form.instance.pk %}
                                    Сохранить
                                {% else %}
                                    Добавить
                                {% endif %}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
{% block title %}Подписки{% endblock %}
{% block content %}
{% cache 20 index_page with page_obj %}
    <div class="container">
        <h1>Подписки</h1>
        {% include 'posts/includes/switcher.html' %}
        {% for post in page_obj %}
          {% include 'includes/post.html' %}
                {% if post.group %}
                    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{post.group.title}}</a>
                {% endif %}
            </article>
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
{% endcache %}         
        {% include 'posts/includes/paginator.html' %}
    </div>   
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}{{ group.title }}{% endblock %}
{% block content %}
    <div class="container">
        <h1>{{ group.title }}</h1>
        <p>
            {{ group.description|linebreaks }}
        </p>
        {% for post in page_obj %}
          {% include 'includes/post.html' %}
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
    </div>    
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% cache 20 index_page with page_obj %}

    <div class="container">
        <h1>Последние обновления на сайте</h1>
        {% include 'posts/includes/switcher.html' %}
        {% for post in page_obj %}
          {% include 'includes/post.html' %}
                {% if post.group %}
                    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{post.group.title}}</a>
                {% endif %}
            </article>
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% endcache %} 
        {% include 'posts/includes/paginator.html' %}
    </div>  
{% endblock %}

yatube/templates/posts/post_delete.html
{% extends 'base.html' %}
{% block title %}Удаление записи{% endblock %}
{% block content %}
    <h1>Удаление записи</h1>
    <form action="" method="post">{% csrf_token %}
      <p>Вы уверены, что хотите удалить "{{ post.text }}"?</p>
      <input class="btn btn-primary" type="submit" value="Удалить" />
    </form>
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}Пост {{ title }} {% endblock %}
{% block content %}
    <div class="container py-5">
        <div class="row">
            <aside class="col-12 col-md-3">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
                    {% if post.group %}
                        <li class="list-group-item">
                            Группа: {{ post.group.title }}
                            <br>
                            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
                        {% endif %}
                    </li>
                    <li class="list-group-item">Автор: {{ post.author.get_full_name }}</li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Всего постов автора: {{ posts_amount }}
                    </li>
                    <li class="list-group-item">
                        <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
                    </li>
                </ul>
            </aside>
            <article class="col-12 col-md-9">
                {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
                <p>
                    {{ post.text|linebreaks }}
                </p>
                {% if  post.author == request.user %}
                <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">Редактировать</a>
                <a class="btn btn-primary" href="{% url 'posts:post_delete' post.id %}">Удалить запись</a>
                {% endif %}
                {% if user.is_authenticated %}
                <div class="card my-4">
                  <h5 class="card-header">Добавить комментарий:</h5>
                  <div class="card-body">
                    <form method="post" action="{% url 'posts:add_comment' post.id %}">
                      {% csrf_token %}      
                      <div class="form-group mb-2">
                        {{ form.text|addclass:"form-control" }}
                      </div>
                      <button type="submit" class="btn btn-primary">Отправить</button>
                    </form>
                  </div>
                </div>
              {% endif %}
              
              {% for comment in comments %}
                <div class="media mb-4">
                  <div class="media-body">
                    <h5 class="mt-0">
                      <a href="{% url 'posts:profile' comment.author.username %}">
                        {{ comment.author.username }}
                      </a>
                    </h5>
                      <p>
                       {{ comment.text|linebreaks }}
                      </p>
                    </div>
                  </div>
              {% endfor %} 
            </article>
        </div>
    </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} Профайл пользователя {{ author.get_full_name }}{% endblock %}
{% block content %}
<div class="container py-5">        
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ posts_amount }}</h3>
    {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
   {% endif %}
    {% for post in page_obj %}
    {% include 'includes/post.html' %}
    {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
</div>    
{% endblock %}